# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
    exclude: '(^lib/)|(svg$)'
  - id: end-of-file-fixer
    exclude: '(^lib/)|(svg$)'
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.7  # Use the ref you want to point at
  hooks:
  - id: mdformat
    args: [--number, --wrap=80]
    additional_dependencies:
    - mdformat-frontmatter
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks
    autofix_prs: true
    autoupdate_schedule: monthly
    skip: []
    submodules: false